/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dados.MembroDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import negocio.Membro;

/**
 *
 * @author Arlindo
 */
public class Buscas extends javax.swing.JPanel {

    /**
     * Creates new form Buscas
     */
    private String msg_busca = "Digite o nome do Membro";
    private Color bgcolor;
    Membro c;
    DefaultTableModel modelo;
    Dimension dimensao;
    
    public Buscas() throws Exception {
        initComponents();
        jT_busca.setText(msg_busca);
        this.dimensao = this.getToolkit().getScreenSize();
//        jL_titulo.setSize((int) dimensao.getWidth(),80);
        float [] hsb = new float[3];
        Color.RGBtoHSB(242,241,240,hsb);
        this.bgcolor = Color.getHSBColor(hsb[0],hsb[1],hsb[2]);
        jDesktopPane1.setBackground(this.bgcolor);
       // jB_disciplina.setEnabled(false);
        atualizarLista("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jB_GMembro = new javax.swing.JButton();
        jS_lista = new javax.swing.JScrollPane();
        jT_lista = new javax.swing.JTable();
        jT_busca = new javax.swing.JTextField();

        jB_GMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/+.png"))); // NOI18N
        jB_GMembro.setMnemonic('g');
        jB_GMembro.setText("Ger. Membro");
        jB_GMembro.setToolTipText("Gerenciar Clientes");
        jB_GMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GMembroActionPerformed(evt);
            }
        });
        jB_GMembro.setBounds(50, 600, 160, 80);
        jDesktopPane1.add(jB_GMembro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jS_lista.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jT_lista.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jT_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jT_lista.setRowHeight(18);
        jT_lista.setRowMargin(4);
        jT_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_listaMouseClicked(evt);
            }
        });
        jT_lista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_listaFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_listaFocusGained(evt);
            }
        });
        jS_lista.setViewportView(jT_lista);

        jS_lista.setBounds(50, 140, 760, 440);
        jDesktopPane1.add(jS_lista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jT_busca.setForeground(new java.awt.Color(187, 187, 187));
        jT_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_buscaFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_buscaFocusGained(evt);
            }
        });
        jT_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_buscaKeyReleased(evt);
            }
        });
        jT_busca.setBounds(50, 90, 760, 40);
        jDesktopPane1.add(jT_busca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_GMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GMembroActionPerformed
        int numLinhaSelecionada = jT_lista.getSelectedRow();
        String cpf = jT_lista.getValueAt(numLinhaSelecionada, 1).toString();

        MembroDAO cD = new MembroDAO();
        c = cD.buscaMembro(cpf);

        //        CadastroMembro cm = new CadastroMembro(c);
        //                cm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //                Toolkit theKit = cm.getToolkit(); // for Fullscreen
        //                cm.setBounds(new Rectangle(theKit.getScreenSize()));
        //                cm.setVisible(true);
        new GerenciarMembro(bgcolor,c).setVisible(true);
        
        JPanel window = new CadastroMembroP(c);
        this.removeAll();
        this.set
        this.setContentPane(window);  
        this.pack(); 

        //this.dispose();
    }//GEN-LAST:event_jB_GMembroActionPerformed

     public void atualizarLista(String nome) throws Exception{
        

        
        String [] colunas = new String []{"Nome","CPF","Telefone","Endereco"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        
         MembroDAO f = new MembroDAO();
         List listar = f.listaMembro(nome);
        if(listar.isEmpty()){
           // jB_disciplina.setEnabled(false);
            //jB_excluir.setVisible(false);
            
        }
        
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Membro l = (Membro)it.next();
            modelo.addRow(new Object[]{l.getNome(),l.getCpf(),l.getTelefone(),l.getCongregacao()});
        }
        
        
        jT_lista.setModel(modelo);
        jT_lista.setShowHorizontalLines(false);
        jT_lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jT_lista.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jT_lista.getColumnModel().getColumn(2).setPreferredWidth((int) (0.17*jS_lista.getSize().getWidth()));  
        jT_lista.getColumnModel().getColumn(1).setPreferredWidth((int) (0.30*jS_lista.getSize().getWidth()));  
        jT_lista.getColumnModel().getColumn(3).setPreferredWidth((int) (0.59*jS_lista.getSize().getWidth())); 
     }
    
    private void jT_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_listaMouseClicked
        // TODO add your handling code here:
        int numLinhaSelecionada = jT_lista.getSelectedRow();
        String cpf = jT_lista.getValueAt(numLinhaSelecionada, 1).toString();

        MembroDAO cD = new MembroDAO();
        c = cD.buscaMembro(cpf);
        //jB_disciplina.setEnabled(true);

        //jT_endereco.setText(c.getEndereco());
    }//GEN-LAST:event_jT_listaMouseClicked

    private void jT_listaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_listaFocusLost
        // TODO add your handling code here:

        int numLinhaSelecionada = jT_lista.getSelectedRow();
        String cpf = jT_lista.getValueAt(numLinhaSelecionada, 1).toString();

        MembroDAO cD = new MembroDAO();
        c = cD.buscaMembro(cpf);
        //jB_novo_pedido.setEnabled(true);

        // jT_endereco.setText(c.getEndereco());
    }//GEN-LAST:event_jT_listaFocusLost

    private void jT_listaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_listaFocusGained
        // TODO add your handling code here:
        int numLinhaSelecionada = jT_lista.getSelectedRow();
        String cpf = jT_lista.getValueAt(numLinhaSelecionada, 1).toString();

        MembroDAO cD = new MembroDAO();
        c = cD.buscaMembro(cpf);

        //jT_endereco.setText(c.getEndereco());
    }//GEN-LAST:event_jT_listaFocusGained

    private void jT_buscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_buscaFocusLost
        if(jT_busca.getText().isEmpty())
        {
            jT_busca.setForeground(Color.gray);
            jT_busca.setText(msg_busca);
        }
    }//GEN-LAST:event_jT_buscaFocusLost

    private void jT_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_buscaFocusGained
        if(jT_busca.getText().equals(msg_busca)){
            jT_busca.setText("");
            jT_busca.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jT_buscaFocusGained

    private void jT_buscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_buscaKeyReleased
        if(!jT_busca.getText().isEmpty()){
            jT_busca.setForeground(Color.BLACK);
        }

        String filtro = jT_busca.getText();
        try {

            atualizarLista(filtro);
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jT_buscaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_GMembro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jS_lista;
    private javax.swing.JTextField jT_busca;
    private javax.swing.JTable jT_lista;
    // End of variables declaration//GEN-END:variables
}
