/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dados.MembroDAO;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.imageio.spi.ServiceRegistry;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import base.Base;
import base.Data;
import base.ExpressaoRegular;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.text.ParseException; 
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import negocio.Membro;

/**
 *
 * @author Arlindo
 */
public class CadastroMembro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMembro
     */
    MaskFormatter formatoDataNascimento, formatotelefone, formatocpf;
    Membro m;
    public CadastroMembro(Membro m) {
        initComponents();
        this.m = m;
        jFormattedTextFieldCPF.setText(m.getCpf());
        jFormattedTextFieldDataBatis.setText(m.getDataBatismo());
        jFormattedTextFieldDataNasc.setText(m.getDataNascimento());
        jFormattedTextField_telefone.setText(m.getTelefone());
        jTextFieldNome.setText(m.getNome());
        jTextFieldCongregacao.setText(m.getCongregacao()); 
        jTextFieldRG.setText(m.getRg());
        jTextFieldNomedoPai.setText(m.getNomeDoPai());
        jTextFieldNomedaMae.setText(m.getNomeDaMae());
        jTextFieldNaturalidade.setText(m.getNaturalidade());
        jComboBox_sexo.setSelectedItem(m.getSexo());
        
        
        jPanelTitulo.setToolTipText("Gerenciar Membro");
        jLabelTitulo.setText("Gerenciar Membro");
        jButtonSalvar.setText("Atualizar");
        
        this.setAlwaysOnTop(true);
        
    }
    
    public CadastroMembro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelNomedoPai = new javax.swing.JLabel();
        jTextFieldNomedoPai = new javax.swing.JTextField();
        jLabelNomedaMae = new javax.swing.JLabel();
        jTextFieldNomedaMae = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabelDataBat = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelCongregacao = new javax.swing.JLabel();
        jTextFieldCongregacao = new javax.swing.JTextField();
        jLabelNaturalidade = new javax.swing.JLabel();
        jTextFieldNaturalidade = new javax.swing.JTextField();
        jComboBox_sexo = new javax.swing.JComboBox();
        jLabelSexo = new javax.swing.JLabel();
        jButtonSelecionaFoto = new javax.swing.JButton();
        jLabelFoto = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldDataBatis = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel_msg_cpf = new javax.swing.JLabel();
        jLabel_msg_nome = new javax.swing.JLabel();
        jLabel_msg_nomePai = new javax.swing.JLabel();
        jLabel_msg_dataNasc = new javax.swing.JLabel();
        jLabel_msg_congregacao = new javax.swing.JLabel();
        jLabel_msg_naturalidade = new javax.swing.JLabel();
        jLabel_msg_telefone = new javax.swing.JLabel();
        jLabel_msg_dataBatis = new javax.swing.JLabel();
        jLabel_msg_dataBatismo1 = new javax.swing.JLabel();
        jLabel_msg_nomeMae = new javax.swing.JLabel();
        try{      formatotelefone = new MaskFormatter("(##)####-####");   }catch(Exception erro){       JOptionPane.showMessageDialog(null,"Erro ao inserir o Telefone");   }
        jFormattedTextField_telefone = new JFormattedTextField(formatotelefone);
        jLabelTelefone = new javax.swing.JLabel();
        jLabel_msg_RG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Cadastro de Membro");

        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelNomedoPai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomedoPai.setText("Nome do Pai");

        jTextFieldNomedoPai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomedoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomedoPaiActionPerformed(evt);
            }
        });
        jTextFieldNomedoPai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomedoPaiFocusLost(evt);
            }
        });

        jLabelNomedaMae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomedaMae.setText("Nome da Mãe");

        jTextFieldNomedaMae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomedaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomedaMaeActionPerformed(evt);
            }
        });
        jTextFieldNomedaMae.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomedaMaeFocusLost(evt);
            }
        });

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCPF.setText("CPF");

        jLabelRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRG.setText("RG");

        jTextFieldRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRGActionPerformed(evt);
            }
        });
        jTextFieldRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRGFocusLost(evt);
            }
        });

        jLabelDataBat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataBat.setText("Data de Batismo");

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataNasc.setText("Data de Nascimento");

        jLabelCongregacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCongregacao.setText("Congregação");

        jTextFieldCongregacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCongregacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCongregacaoActionPerformed(evt);
            }
        });
        jTextFieldCongregacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCongregacaoFocusLost(evt);
            }
        });

        jLabelNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNaturalidade.setText("Naturalidade");

        jTextFieldNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNaturalidadeActionPerformed(evt);
            }
        });
        jTextFieldNaturalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNaturalidadeFocusLost(evt);
            }
        });

        jComboBox_sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino" }));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSexo.setText("Sexo");

        jButtonSelecionaFoto.setText("Selecionar Foto");
        jButtonSelecionaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionaFotoActionPerformed(evt);
            }
        });

        jLabelFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jFormattedTextFieldDataBatis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldDataBatis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFormattedTextFieldDataBatis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataBatisFocusLost(evt);
            }
        });

        jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataNascFocusLost(evt);
            }
        });

        jFormattedTextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });
        jFormattedTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCPFFocusLost(evt);
            }
        });

        jLabel_msg_cpf.setForeground(java.awt.Color.red);

        jLabel_msg_nome.setForeground(java.awt.Color.red);

        jLabel_msg_nomePai.setForeground(java.awt.Color.red);

        jLabel_msg_dataNasc.setForeground(java.awt.Color.red);

        jLabel_msg_congregacao.setForeground(java.awt.Color.red);

        jLabel_msg_naturalidade.setForeground(java.awt.Color.red);

        jLabel_msg_telefone.setForeground(java.awt.Color.red);

        jLabel_msg_dataBatis.setForeground(java.awt.Color.red);

        jLabel_msg_dataBatismo1.setForeground(java.awt.Color.red);

        jLabel_msg_nomeMae.setForeground(java.awt.Color.red);

        jFormattedTextField_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField_telefoneFocusLost(evt);
            }
        });
        jFormattedTextField_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_telefoneKeyReleased(evt);
            }
        });

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefone.setText("Telefone");

        jLabel_msg_RG.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(304, 304, 304)
                                        .addComponent(jLabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelCongregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCongregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabel_msg_dataBatis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_msg_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_msg_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonSelecionaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldDataBatis))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_msg_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabel_msg_congregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(198, 198, 198))
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNaturalidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_msg_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextFieldNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFormattedTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel_msg_naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel_msg_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelNomedaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNomedaMae))
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelDataBat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_msg_nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_msg_nomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel_msg_dataBatismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_msg_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addComponent(jLabel_msg_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_msg_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jComboBox_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                                        .addComponent(jLabelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_msg_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFormattedTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel_msg_naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_msg_congregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCongregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCongregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSelecionaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDataBat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldDataBatis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_msg_dataBatis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_msg_dataBatismo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTituloLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_msg_nomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNomedaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNomedaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_msg_nomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNomedoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel_msg_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFFocusLost
        String t = jFormattedTextFieldCPF.getText().replace(".","").replace("-","").trim();
        System.out.println(t);
        this.cpfValido = (t.length() == 11);
        if(this.cpfValido && base.validaCPF(t)){
            jLabel_msg_cpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            jLabel_msg_cpf.setText("");
            System.out.println(t);
        }
        else {
            jLabel_msg_cpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            jLabel_msg_cpf.setText("CPF inválido");
        }
        jButtonSalvar.setEnabled(this.camposValidos());
    }//GEN-LAST:event_jFormattedTextFieldCPFFocusLost

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
            // TODO add your handling code here:
           this.dispose();
           
//                Principal principal = new Principal();
//                principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                Toolkit theKit = principal.getToolkit(); // for Fullscreen  
//                principal.setBounds(new Rectangle(theKit.getScreenSize()));
//                principal.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CadastroMembro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (jButtonSalvar.getText().equals("Atualizar")){
            Membro m1;
            MembroDAO mD = new MembroDAO();
            String sexo = jComboBox_sexo.getSelectedItem().toString();
            m1 = new Membro(jTextFieldNome.getText(), jFormattedTextFieldDataBatis.getText(),jTextFieldCongregacao.getText(), jTextFieldRG.getText(), jFormattedTextFieldCPF.getText(), jFormattedTextFieldDataNasc.getText(), jTextFieldNomedoPai.getText(), jTextFieldNomedaMae.getText(), jTextFieldNaturalidade.getText(), sexo, "ATIVO",jFormattedTextField_telefone.getText());
            if(mD.cadastraMembro(m1,m.getId())){
                System.out.println("Salvou");
            }
        }else{
            Membro m;
            MembroDAO mD = new MembroDAO();
            String sexo = jComboBox_sexo.getSelectedItem().toString();
            m = new Membro(jTextFieldNome.getText(), jFormattedTextFieldDataBatis.getText(),jTextFieldCongregacao.getText(), jTextFieldRG.getText(), jFormattedTextFieldCPF.getText(), jFormattedTextFieldDataNasc.getText(), jTextFieldNomedoPai.getText(), jTextFieldNomedaMae.getText(), jTextFieldNaturalidade.getText(), sexo, "ATIVO",jFormattedTextField_telefone.getText());
            if(mD.cadastraMembro(m)){
                System.out.println("Salvou");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSelecionaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionaFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Importar imagem");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        // int a = fileChooser.showOpenDialog(null);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File arquivo = fileChooser.getSelectedFile();//arquivo
            BufferedImage bi = null;
            try {
                bi = ImageIO.read(arquivo); //carrega a imagem real num buffer
            } catch (IOException ex) {
                System.out.println("Erro");
            }
            BufferedImage aux = new BufferedImage(150, 120, bi.getType());//cria um buffer auxiliar com o tamanho desejado
            Graphics2D g = aux.createGraphics();//pega a classe graphics do aux para edicao
            AffineTransform at = AffineTransform.getScaleInstance((double) 150 / bi.getWidth(), (double) 120 / bi.getHeight());//cria a transformacao
            g.drawRenderedImage(bi, at);//pinta e transforma a imagem real no auxiliar
            jLabelFoto.setIcon(new ImageIcon(aux));//seta no jlabel
        }
    }//GEN-LAST:event_jButtonSelecionaFotoActionPerformed

    private void jTextFieldNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNaturalidadeActionPerformed

    private void jTextFieldCongregacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCongregacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCongregacaoActionPerformed

    private void jTextFieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGActionPerformed

    private void jTextFieldNomedaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomedaMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomedaMaeActionPerformed

    private void jTextFieldNomedoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomedoPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomedoPaiActionPerformed

    private void jFormattedTextFieldDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascFocusLost
        // TODO add your handling code here:
        String t = jFormattedTextFieldDataNasc.getText().trim();
        if (!t.equals("")){
            jLabel_msg_dataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.dataNascValida = true;
        }else{
            jLabel_msg_dataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.dataNascValida = false;
        }
    }//GEN-LAST:event_jFormattedTextFieldDataNascFocusLost

        
    private void jFormattedTextFieldDataBatisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataBatisFocusLost
        // TODO add your handling code here:
        String t = jFormattedTextFieldDataBatis.getText().trim();
        if (!t.equals("")){
            jLabel_msg_dataBatismo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.dataBastismoValida = true;
        }else{
            jLabel_msg_dataBatismo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.dataBastismoValida = false;
        }
    }//GEN-LAST:event_jFormattedTextFieldDataBatisFocusLost

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        // TODO add your handling code here:
        String t = jTextFieldNome.getText().trim();
        if (!t.equals("")){
            jLabel_msg_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.nomeValido = true;
        }else{
            jLabel_msg_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.nomeValido = false;
        }
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldNomedoPaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomedoPaiFocusLost
        // TODO add your handling code here:
        String t = jTextFieldNomedoPai.getText().trim();
        if (!t.equals("")){
            jLabel_msg_nomePai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.nomePaiValido = true;
        }else{
            jLabel_msg_nomePai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.nomePaiValido = false;
        }
    }//GEN-LAST:event_jTextFieldNomedoPaiFocusLost

    private void jTextFieldCongregacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCongregacaoFocusLost
        // TODO add your handling code here:
        String t = jTextFieldNomedaMae.getText().trim();
        if (!t.equals("")){
            jLabel_msg_congregacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.congregacaoValida = true;
        }else{
            jLabel_msg_congregacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.congregacaoValida = false;
        }
    }//GEN-LAST:event_jTextFieldCongregacaoFocusLost

    private void jTextFieldRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRGFocusLost
        // TODO add your handling code here:
        String t = jTextFieldRG.getText().trim();
        if (!t.equals("")){
            jLabel_msg_RG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.rgValida = true;
        }else{
            jLabel_msg_RG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.rgValida = false;
        }
    }//GEN-LAST:event_jTextFieldRGFocusLost

    private void jFormattedTextField_telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefoneFocusLost
        this.telefoneValido = (jFormattedTextField_telefone.getText().replace("(","").replace(")","").replace("-","").trim().length() == 10);
        if(this.telefoneValido){
            jLabel_msg_telefone.setIcon(null);
            jLabel_msg_telefone.setText("");
        }
        else {
            jLabel_msg_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            //jLabel_msg_telefone.setText("Telefone inválido");
        }
        jButtonSalvar.setEnabled(this.camposValidos());
    }//GEN-LAST:event_jFormattedTextField_telefoneFocusLost

    private void jFormattedTextField_telefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefoneKeyReleased
        this.telefoneValido = (jFormattedTextField_telefone.getText().replace("(","").replace(")","").replace("-","").trim().length() == 10);
        if(this.telefoneValido){
            jLabel_msg_telefone.setIcon(null);
            jLabel_msg_telefone.setText("");
        }
        else {
            jLabel_msg_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
           // jLabel_msg_telefone.setText("Telefone inválido");
        }
        jButtonSalvar.setEnabled(this.camposValidos());
    }//GEN-LAST:event_jFormattedTextField_telefoneKeyReleased

    private void jTextFieldNaturalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNaturalidadeFocusLost
        // TODO add your handling code here:
         String t = jTextFieldNaturalidade.getText().trim();
        if (!t.equals("")){
            jLabel_msg_naturalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.naturalaidadeValida = true;
        }else{
            jLabel_msg_naturalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.naturalaidadeValida = false;
        }
    }//GEN-LAST:event_jTextFieldNaturalidadeFocusLost

    private void jTextFieldNomedaMaeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomedaMaeFocusLost
        // TODO add your handling code here:
         String t = jTextFieldNomedaMae.getText().trim();
        if (!t.equals("")){
            jLabel_msg_nomeMae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16x16.png")));
            this.nomeMaeValido = true;
        }else{
            jLabel_msg_nomeMae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            this.nomeMaeValido = false;
        }
    }//GEN-LAST:event_jTextFieldNomedaMaeFocusLost

     private void jFormattedTextField_cpfFocusLost(java.awt.event.FocusEvent evt) {                                                  
        String t = jFormattedTextFieldCPF.getText().replace(".","").replace("-","").trim();
        this.cpfValido = (t.length() == 11);
        if(this.cpfValido && base.validaCPF(t)){
            jLabel_msg_cpf.setIcon(null);
            jLabel_msg_cpf.setText("");
        } 
        else {
            jLabel_msg_cpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
           // jLabel_msg_cpf.setText("CPF inválido");
        }
        jButtonSalvar.setEnabled(this.camposValidos());
    }               
    
              
        
    private boolean camposValidos(){
        return this.nomeValido && this.dataNascValida && telefoneValido && congregacaoValida && cpfValido && naturalaidadeValida && nomeMaeValido && nomePaiValido && rgValida;
    }
    
    private boolean nomeValido = false, dataNascValida = false,dataBastismoValida = false, cpfValido = false, telefoneValido = false, nomePaiValido = false, nomeMaeValido = false, naturalaidadeValida = false; 
    private boolean congregacaoValida = false, rgValida = false;
    private Base base =  new Base();
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionaFoto;
    private javax.swing.JComboBox jComboBox_sexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataBatis;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextField_telefone;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCongregacao;
    private javax.swing.JLabel jLabelDataBat;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNaturalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomedaMae;
    private javax.swing.JLabel jLabelNomedoPai;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabel_msg_RG;
    private javax.swing.JLabel jLabel_msg_congregacao;
    private javax.swing.JLabel jLabel_msg_cpf;
    private javax.swing.JLabel jLabel_msg_dataBatis;
    private javax.swing.JLabel jLabel_msg_dataBatismo1;
    private javax.swing.JLabel jLabel_msg_dataNasc;
    private javax.swing.JLabel jLabel_msg_naturalidade;
    private javax.swing.JLabel jLabel_msg_nome;
    private javax.swing.JLabel jLabel_msg_nomeMae;
    private javax.swing.JLabel jLabel_msg_nomePai;
    private javax.swing.JLabel jLabel_msg_telefone;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTextFieldCongregacao;
    private javax.swing.JTextField jTextFieldNaturalidade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomedaMae;
    private javax.swing.JTextField jTextFieldNomedoPai;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables
}
