/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import Dados.DisciplinaDAO;
import java.awt.Color;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import negocio.Disciplina;
import negocio.Membro;

/**
 *
 * @author massilva
 */
public class GerenciarMembro extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Color bgcolor;
    Membro m;
    
    /**
     * Creates new form ListarCliente
     */
    public GerenciarMembro(Color bgcolor, Membro m) {
         initComponents();
        
        this.m = m;
        this.bgcolor = bgcolor;
        jDesktopPane1.setBackground(bgcolor);
        
        jL_titulo.setText(m.getNome());
        jL_Telefone.setText(m.getTelefone());
        jL_Congregacao.setText(m.getCongregacao());
        jL_Endereco.setText("FALTA ENDEREÇO!!!");
        
        try {
            atualizarLista();
        } catch (Exception ex) {
            Logger.getLogger(GerenciarMembro.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jL_titulo = new javax.swing.JLabel();
        jS_lista = new javax.swing.JScrollPane();
        jT_lista = new javax.swing.JTable();
        jB_Adicionar = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jL_Congregacao = new javax.swing.JLabel();
        jL_EnderecoN = new javax.swing.JLabel();
        jL_TelefoneN = new javax.swing.JLabel();
        jL_Telefone = new javax.swing.JLabel();
        jL_CongregacaoN = new javax.swing.JLabel();
        jL_Cargo = new javax.swing.JLabel();
        jL_Endereco = new javax.swing.JLabel();
        jB_Adicionar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Clientes");
        setAlwaysOnTop(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jL_titulo.setFont(new java.awt.Font("Ume Mincho S3", 1, 48)); // NOI18N
        jL_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_titulo.setText("Membro");
        jL_titulo.setBounds(0, 0, 900, 80);
        jDesktopPane1.add(jL_titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jT_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jS_lista.setViewportView(jT_lista);

        jS_lista.setBounds(40, 310, 630, 300);
        jDesktopPane1.add(jS_lista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/+.png"))); // NOI18N
        jB_Adicionar.setMnemonic('e');
        jB_Adicionar.setText("Adic. Disciplina");
        jB_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AdicionarActionPerformed(evt);
            }
        });
        jB_Adicionar.setBounds(700, 310, 160, 80);
        jDesktopPane1.add(jB_Adicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/text_edit.png"))); // NOI18N
        jB_editar.setMnemonic('e');
        jB_editar.setText("Editar");
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });
        jB_editar.setBounds(700, 420, 160, 80);
        jDesktopPane1.add(jB_editar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/remove.png"))); // NOI18N
        jB_voltar.setMnemonic('f');
        jB_voltar.setText("Fechar");
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });
        jB_voltar.setBounds(700, 530, 160, 80);
        jDesktopPane1.add(jB_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_Congregacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Congregacao.setBounds(160, 170, 720, 40);
        jDesktopPane1.add(jL_Congregacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_EnderecoN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_EnderecoN.setText("Endereço:");
        jL_EnderecoN.setBounds(40, 80, 90, 40);
        jDesktopPane1.add(jL_EnderecoN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_TelefoneN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_TelefoneN.setText("Telefone:");
        jL_TelefoneN.setBounds(40, 120, 90, 40);
        jDesktopPane1.add(jL_TelefoneN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_Telefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Telefone.setBounds(140, 120, 240, 40);
        jDesktopPane1.add(jL_Telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_CongregacaoN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_CongregacaoN.setText("Congregação:");
        jL_CongregacaoN.setBounds(40, 170, 110, 30);
        jDesktopPane1.add(jL_CongregacaoN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_Cargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Cargo.setText("Cargo:");
        jL_Cargo.setBounds(410, 130, 90, 30);
        jDesktopPane1.add(jL_Cargo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_Endereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Endereco.setBounds(140, 80, 750, 40);
        jDesktopPane1.add(jL_Endereco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_Adicionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/+.png"))); // NOI18N
        jB_Adicionar1.setMnemonic('e');
        jB_Adicionar1.setText("Alterar Dados do Membro");
        jB_Adicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Adicionar1ActionPerformed(evt);
            }
        });
        jB_Adicionar1.setBounds(40, 220, 200, 70);
        jDesktopPane1.add(jB_Adicionar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void atualizarLista() throws Exception{
        
        String [] colunas = new String []{"#","Nome","Status"};
        modelo = new DefaultTableModel(null, colunas){
            
            @Override
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        
        DisciplinaDAO p = new DisciplinaDAO();
        List listar = p.listaDisciplinaIdCliente(m);
        
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Disciplina l = (Disciplina)it.next();
            modelo.addRow(new Object[]{l.getId(),l.getDataInicio(),l.getStatus()});
        }
        
        jT_lista.setModel(modelo);
        jT_lista.setShowHorizontalLines(false);
        jT_lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jT_lista.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jT_lista.getColumnModel().getColumn(1).setPreferredWidth(120);  
    }
    
    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_voltarActionPerformed

    private void jB_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AdicionarActionPerformed
        // TODO add your handling code here:
        
        new Cadastrodisciplina(m).setVisible(rootPaneCheckingEnabled);
        this.setAlwaysOnTop(false);
        this.dispose();
      //new CadastroPedido(this,true,this.bgcolor,this.cliente).setVisible(true);
    }//GEN-LAST:event_jB_AdicionarActionPerformed

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
//        try {
//            this.setAlwaysOnTop(false);
//            int numLinhaSelecionada = jT_lista.getSelectedRow();
//            int id = Integer.parseInt(jT_lista.getValueAt(numLinhaSelecionada, 0).toString());
//            JDialog dialogo = new EditarPedido(this,true,id);
//            dialogo.setVisible(true);
//            this.setAlwaysOnTop(false);
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(this,"Por favor, selecione o pedido.");
//        }
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jB_Adicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Adicionar1ActionPerformed
        // TODO add your handling code here:
        new CadastroMembro(m).setVisible(true);
        this.setAlwaysOnTop(false);
    }//GEN-LAST:event_jB_Adicionar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Adicionar;
    private javax.swing.JButton jB_Adicionar1;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jL_Cargo;
    private javax.swing.JLabel jL_Congregacao;
    private javax.swing.JLabel jL_CongregacaoN;
    private javax.swing.JLabel jL_Endereco;
    private javax.swing.JLabel jL_EnderecoN;
    private javax.swing.JLabel jL_Telefone;
    private javax.swing.JLabel jL_TelefoneN;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JScrollPane jS_lista;
    private javax.swing.JTable jT_lista;
    // End of variables declaration//GEN-END:variables
}
